version: "2.12.1"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app:/node_modules

  sender:
    build: ./sender
    container_name: sender_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
